### Backend local
### Login y obtención del token
POST http://127.0.0.1:3000/api/login
Content-Type: application/json

{
  "email": "tarless@gmail.com",
  "password": "12345678"
}

### Agregar address
POST http://127.0.0.1:3000/api/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbi5nZGwtcGxhY2VAZ2RscGxhY2UuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc1NzgxMjUxLCJleHAiOjE3NzU4MjQ0NTF9.WFZd9EFCcki21Zx7UMQtHSIFiNvcFNEcnyE1oUWB9V8
Content-Type: application/json

{
    "id_user": 3,
    "tipo": "Trabajo",
    "street": "Penitenciaria 225",
    "neighborhood": "Centro",
    "city": "Guadalajara",
    "state": "Jalisco",
    "zipcode": "44100",
    "isdefault": true
}

### Modificar address
PUT http://127.0.0.1:3000/api/address/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbi5nZGwtcGxhY2VAZ2RscGxhY2UuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc1NzgxMjUxLCJleHAiOjE3NzU4MjQ0NTF9.WFZd9EFCcki21Zx7UMQtHSIFiNvcFNEcnyE1oUWB9V8
Content-Type: application/json

{
    "id_user": 3,
    "tipo": "Casa",
    "street": "Lopez Mateos 3225",
    "neighborhood": "La Calma",
    "city": "Zapopan",
    "state": "Jalisco",
    "zipcode": "45200",
    "isdefault": true
}

### Listar direcciones por usuario
GET http://127.0.0.1:3000/api/MetodosPago/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0YXJsZXNzQGdtYWlsLmNvbSIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3NzYwNTY5ODgsImV4cCI6MTc3NjEwMDE4OH0.yIlX9sD_li52x3Kd0vxZM5c-018VmDQLDABv6VDZHZE
Content-Type: application/json

### Listar direcciones por usuario
GET http://127.0.0.1:3000/api/MetodosPagoByUser/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0YXJsZXNzQGdtYWlsLmNvbSIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3NzYxMjQ4MzAsImV4cCI6MTc3NjE2ODAzMH0.cKDSodGiQYUy883IAjyhU-mC4z0N5Liu9C2CpVBjBBk
Content-Type: application/json

### Modificar address
POST http://127.0.0.1:3000/api/metodosPago
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0YXJsZXNzQGdtYWlsLmNvbSIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3NzYwNTY5ODgsImV4cCI6MTc3NjEwMDE4OH0.yIlX9sD_li52x3Kd0vxZM5c-018VmDQLDABv6VDZHZE
Content-Type: application/json

{
    "id_user": 3,
    "type": "visa",
    "last_four": "9876",
    "expiry_date": "10/26",
    "holder_name": "Carlos Armando Grajeda González",
    "isdefault": false
}


### Modificar address
PUT http://127.0.0.1:3000/api/metodosPago/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0YXJsZXNzQGdtYWlsLmNvbSIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3NzYwNTY5ODgsImV4cCI6MTc3NjEwMDE4OH0.yIlX9sD_li52x3Kd0vxZM5c-018VmDQLDABv6VDZHZE
Content-Type: application/json

{
    "id": 1,
    "id_user": 3,
    "type": "mastercard",
    "last_four": "6166",
    "expiry_date": "06/27",
    "holder_name": "Marco Antonio González Solis",
    "isdefault": true
  }